 ;

/**
 * @Problem Find the nth term in Look-and-say (Or Count and Say) Sequence. The
 *          look-and-say sequence is the sequence of the below integers: 1, 11,
 *          21, 1211, 111221, 312211, 13112221, 1113213211, ...
 * 
 *          How is the above sequence generated?
 *          The nth term is generated by reading (n-1)th term.
 * 
 *          The first term is "1"
 *          Second term is "11", generated by reading first term as "One 1"
 *          (There is one 1 in previous term)
 *          Third term is "21", generated by reading second term as "Two 1"
 *          Fourth term is "1211", generated by reading third term as "One 2 One
 *          1" and so on
 * 
 * @Example Input: n = 3
 *          Output: 21
 *          Explanation: The 3rd term of the sequence is 21
 * 
 *          1st term: 1
 *          2nd term: one 1 -> 11
 *          3rd term: two 1s -> 21
 *          Input: n = 4
 *          Output: 1211
 *          Explanation: The 4th term of the sequence is 1211
 * 
 *          1st term: 1
 *          2nd term: one 1 -> 11
 *          3rd term: two 1s -> 21
 *          4th term: one 2 one 1 -> 1211
 *          Input: n = 1
 *          Output: 1
 *          Explanation: The first term of the sequence is 1
 */
public class LookAndSay {

    public static void main(String args[]) {
        System.out.println(getNSay(4));
    }

    public static String getNSay(int n) {
        if (n == 1)
            return "1";
        String s = "1";
        for (int i = 2; i <= n; i++) {
            s = say(s);
        }
        return s;
    }

    public static String say(String what) {
        int i = 0;
        StringBuilder sb = new StringBuilder();
        while (i < what.length()) {
            int count = 1;
            while (i + 1 < what.length() && what.charAt(i) == what.charAt(i + 1)) {
                count++;
                i++;
            }
            sb.append(count);
            sb.append(what.charAt(i));
            i++;
        }
        return sb.toString();
    }
}
